Seet.create({seet: "1"})
Seet.create({seet: "2"})
Seet.create({seet: "3"})
Seet.create({seet: "4"})
Seet.create({seet: "5"})
Seet.create({seet: "6"})
Seet.create({seet: "7"})
Seet.create({seet: "8"})
Seet.create({seet: "9"})
Seet.create({seet: "10"})
Seet.create({seet: "11"})

Seet.create({seat_fees: "無料"})
Seet.create({seat_fees: "500"})
Seet.create({seat_fees: "1000"})
Seet.create({seat_fees: "1500"})
Seet.create({seat_fees: "2000"})
Seet.create({seat_fees: "2500"})
Seet.create({seat_fees: "3000"})
Seet.create({seat_fees: "3500"})
Seet.create({seat_fees: "4000"})
Seet.create({seat_fees: "4500"})
Seet.create({seat_fees: "5000"})




Recommend.create({text: "パーマかけたい"})
Recommend.create({text: "ショートにしたい"})
Recommend.create({text: "前髪切りたい"})
Recommend.create({text: "月に1回のメンテナンス"})
Recommend.create({text: "毛先を整えたい"})

Base.create({base: "都内23区内"})
Base.create({base: "都内23区外"})
Base.create({base: "千代田区"})
Base.create({base: "中央区"})
Base.create({base: "港区"})
Base.create({base: "新宿区"})
Base.create({base: "文京区"})
Base.create({base: "台東区"})
Base.create({base: "墨田区"})
Base.create({base: "江東区"})
Base.create({base: "品川区"})
Base.create({base: "目黒区"})
Base.create({base: "大田区"})
Base.create({base: "世田谷区"})
Base.create({base: "渋谷区"})
Base.create({base: "中野区"})
Base.create({base: "杉並区"})
Base.create({base: "豊島区"})
Base.create({base: "北区"})
Base.create({base: "荒川区"})
Base.create({base: "板橋区"})
Base.create({base: "練馬区"})
Base.create({base: "足立区"})
Base.create({base: "葛飾区"})
Base.create({base: "江戸川区"})


Hairstyle.create({menu: "ショート"})
Hairstyle.create({menu: "ロング"})
Hairstyle.create({menu: "冠婚葬祭"})
Hairstyle.create({menu: "メンズカット"})
